# Generated by Django 2.1.5 on 2019-02-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='followers',
        ),
        migrations.DeleteModel(
            name='likes',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='followers_quantity',
            new_name='followers_Quantity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='likes_quantity',
            new_name='likes_Quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='picture_link',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='profile_link',
            field=models.CharField(max_length=300),
        ),
    ]
