# Generated by Django 2.1.5 on 2019-02-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190208_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_follower',
            old_name='quantity',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='order_like',
            old_name='quantity',
            new_name='likes',
        ),
    ]
