# Generated by Django 2.1.5 on 2019-02-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190208_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_follower',
            name='status',
            field=models.CharField(default='In Bearbeitung', max_length=100),
        ),
    ]
