# Generated by Django 2.1.5 on 2019-02-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_order_follower_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_follower',
            options={'ordering': ['-date'], 'permissions': (('edit_orders', 'Can edit and see all orders  status etc.'),)},
        ),
    ]
