# Generated by Django 2.1.5 on 2019-02-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190213_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_follower',
            options={'ordering': ['-date'], 'permissions': (('editorders', 'Can edit and see all orders with status etc.'),)},
        ),
    ]
